<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-27T23:50:32 IST" name="Default suite" finished-at="2024-11-27T23:50:38 IST" duration-ms="6068">
    <groups>
    </groups>
    <test started-at="2024-11-27T23:50:32 IST" name="Default test" finished-at="2024-11-27T23:50:38 IST" duration-ms="6068">
      <class name="Test.firstClass">
        <test-method is-config="true" signature="InitWebDriver()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:32 IST" name="InitWebDriver" finished-at="2024-11-27T23:50:34 IST" duration-ms="2357" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitWebDriver -->
        <test-method signature="testFail()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:34 IST" name="testFail" finished-at="2024-11-27T23:50:34 IST" duration-ms="17" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This test will fail expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This test will fail expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Test.firstClass.testFail(firstClass.java:42)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFail -->
        <test-method is-config="true" signature="CloseWD()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:34 IST" name="CloseWD" finished-at="2024-11-27T23:50:35 IST" duration-ms="227" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseWD -->
        <test-method is-config="true" signature="InitWebDriver()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:35 IST" name="InitWebDriver" finished-at="2024-11-27T23:50:35 IST" duration-ms="902" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitWebDriver -->
        <test-method signature="testPass()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:35 IST" name="testPass" finished-at="2024-11-27T23:50:37 IST" duration-ms="1271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPass -->
        <test-method is-config="true" signature="CloseWD()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:37 IST" name="CloseWD" finished-at="2024-11-27T23:50:37 IST" duration-ms="192" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseWD -->
        <test-method is-config="true" signature="InitWebDriver()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:37 IST" name="InitWebDriver" finished-at="2024-11-27T23:50:38 IST" duration-ms="899" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InitWebDriver -->
        <test-method signature="testSkip()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:38 IST" name="testSkip" finished-at="2024-11-27T23:50:38 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[This test is skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: This test is skipped
at Test.firstClass.testSkip(firstClass.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSkip -->
        <test-method is-config="true" signature="CloseWD()[pri:0, instance:Test.firstClass@79924b]" started-at="2024-11-27T23:50:38 IST" name="CloseWD" finished-at="2024-11-27T23:50:38 IST" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseWD -->
      </class> <!-- Test.firstClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
